include:
  - path: ./docker-compose-base.yml
    env_file: ./.env

services:
  server:
    container_name: server
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE__URL=mysql+aiomysql://${DATABASE__USER}:${DATABASE__PASSWORD}@temporal-mysql:3306/${DATABASE__DATABASE}?charset=utf8mb4
      - TEMPORAL__HOST=temporal:7233
      - REDIS_URL=redis://temporal-redis:6379
      - OTLP__ENDPOINT=http://otel-collector:4317
      - STORAGE__MINIO_ENDPOINT=minio:9000
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    networks:
      - temporal-network
    depends_on:
      migration:
        condition: service_completed_successfully
      temporal:
        condition: service_started

  transfer-worker:
    container_name: transfer-worker
    build: .
    volumes:
      - .:/app
    environment:
      - DATABASE__URL=mysql+aiomysql://${DATABASE__USER}:${DATABASE__PASSWORD}@temporal-mysql:3306/${DATABASE__DATABASE}?charset=utf8mb4
      - TEMPORAL__HOST=temporal:7233
      - REDIS_URL=redis://temporal-redis:6379
      - OTLP__ENDPOINT=http://otel-collector:4317
      - STORAGE__MINIO_ENDPOINT=minio:9000
    command: ["python", "-m", "app.workflows.transfer.worker"]
    networks:
      - temporal-network
    depends_on:
      migration:
        condition: service_completed_successfully
      temporal:
        condition: service_started

  translate-worker:
    container_name: translate-worker
    build: .
    volumes:
      - .:/app
    environment:
      - DATABASE__URL=mysql+aiomysql://${DATABASE__USER}:${DATABASE__PASSWORD}@temporal-mysql:3306/${DATABASE__DATABASE}?charset=utf8mb4
      - LLM__OPENAI_API_KEY=${LLM__OPENAI_API_KEY}
      - LLM__OPENAI_BASE_URL=${LLM__OPENAI_BASE_URL}
      - LLM__OPENAI_MODEL=${LLM__OPENAI_MODEL}
      - TEMPORAL__HOST=temporal:7233
      - REDIS_URL=redis://temporal-redis:6379
      - OTLP__ENDPOINT=http://otel-collector:4317
      - STORAGE__MINIO_ENDPOINT=minio:9000
    command: [ "python", "-m", "app.workflows.translate.worker"]
    networks:
      - temporal-network
    depends_on:
      migration:
        condition: service_completed_successfully
      temporal:
        condition: service_started

  dsl-worker:
    container_name: dsl-worker
    build: .
    volumes:
      - .:/app
    environment:
      - DATABASE__URL=mysql+aiomysql://${DATABASE__USER}:${DATABASE__PASSWORD}@temporal-mysql:3306/${DATABASE__DATABASE}?charset=utf8mb4
      - LLM__OPENAI_API_KEY=${LLM__OPENAI_API_KEY}
      - LLM__OPENAI_BASE_URL=${LLM__OPENAI_BASE_URL}
      - LLM__OPENAI_MODEL=${LLM__OPENAI_MODEL}
      - TEMPORAL__HOST=temporal:7233
      - REDIS_URL=redis://temporal-redis:6379
      - OTLP__ENDPOINT=http://otel-collector:4317
      - STORAGE__MINIO_ENDPOINT=minio:9000
      - EMBEDDING__PROVIDER=${EMBEDDING__PROVIDER:-openai}
      - EMBEDDING__OPENAI_MODEL=${EMBEDDING__OPENAI_MODEL}
      - EMBEDDING__OPENAI_API_BASE=${EMBEDDING__OPENAI_API_BASE}
      - EMBEDDING__OPENAI_API_KEY=${EMBEDDING__OPENAI_API_KEY}
      - EMBEDDING__OPENAI_DIMENSION=${EMBEDDING__OPENAI_DIMENSION}
      - EMBEDDING__OLLAMA_MODEL=${OLLAMA_MODEL:-bge-m3}
      - EMBEDDING__OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://host.docker.internal:11434}
      - DOCUMENT_STORE__URL=${DOCUMENT_STORE__URL:-sqlite:///document_store.db}
      - DOCUMENT_STORE__PROVIDER=${DOCUMENT_STORE__PROVIDER:-mysql}
      - VECTOR_STORE__PROVIDER=${VECTOR_STORE__PROVIDER:-opensearch}
      - VECTOR_STORE__OPENSEARCH_HOSTS=["opensearch:9200"]
      - VECTOR_STORE__OPENSEARCH_USER=${VECTOR_STORE__OPENSEARCH_USER:-admin}
      - VECTOR_STORE__OPENSEARCH_PASSWORD=${VECTOR_STORE__OPENSEARCH_PASSWORD}
    command: ["python", "-m", "app.workflows.dsl.worker"]
    networks:
      - temporal-network
    depends_on:
      migration:
        condition: service_completed_successfully
      temporal:
        condition: service_started

  migration:
    container_name: migration
    build: .
    volumes:
      - .:/app
    environment:
      - DATABASE__URL=mysql+aiomysql://${DATABASE__USER}:${DATABASE__PASSWORD}@temporal-mysql:3306/${DATABASE__DATABASE}?charset=utf8mb4
      - DATABASE__USER=${DATABASE__USER:-root}
      - DATABASE__PASSWORD=${DATABASE__PASSWORD:-root}
      - DATABASE__HOST=mysql
      - DATABASE__PORT=3306
      - DATABASE__DATABASE=${DATABASE__DATABASE:-mydb}
    command: ["python", "-m", "scripts.migrate"]
    networks:
      - temporal-network
    depends_on:
      mysql:
        condition: service_healthy