[tool.poetry]
name = "fastapi-session"
version = "0.1.0"
description = ""
authors = ["xiaohuayuan <xiaohuayuan@bytedance.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
