"""add resource

Revision ID: 9c20c362164b
Revises: 38a2d2008f24
Create Date: 2025-01-07 21:16:19.033529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c20c362164b'
down_revision: Union[str, None] = '38a2d2008f24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resources',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('name', sa.String(length=256), nullable=False, comment='资源名称'),
    sa.Column('storage_type', sa.String(length=20), nullable=False, comment='存储类型'),
    sa.Column('resource_type', sa.String(length=20), nullable=False, comment='资源类型'),
    sa.Column('size', sa.Integer(), nullable=False, comment='文件大小(字节)'),
    sa.Column('path', sa.String(length=512), nullable=False, comment='存储路径'),
    sa.Column('mime_type', sa.String(length=128), nullable=False, comment='MIME类型'),
    sa.Column('meta_info', sa.JSON(), nullable=False, comment='元数据'),
    sa.Column('workspace_id', sa.CHAR(length=36), nullable=False),
    sa.Column('user_id', sa.CHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_id'), 'resources', ['id'], unique=False)
    op.create_index(op.f('ix_resources_name'), 'resources', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resources_name'), table_name='resources')
    op.drop_index(op.f('ix_resources_id'), table_name='resources')
    op.drop_table('resources')
    # ### end Alembic commands ###
