"""add constrain

Revision ID: ea6765b15d35
Revises: 73d465f00aeb
Create Date: 2025-01-08 10:27:42.241040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea6765b15d35'
down_revision: Union[str, None] = '73d465f00aeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'datasets', ['name', 'workspace_id'])
    op.create_unique_constraint(None, 'resources', ['name', 'workspace_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resources', type_='unique')
    op.drop_constraint(None, 'datasets', type_='unique')
    # ### end Alembic commands ###
